config/routes.rb
Thredded::Application.routes.draw do
  mount_sextant if Rails.env.development?
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users

  devise_scope :user do
    match '/auth/:provider/callback', to: 'sessions#create'
  end

  get '/auth/failure', to: redirect('/')
  get '/auth/github', as: :auth_github
  put '/identities' => 'identities#update', as: :identity
  post '/mail/receive' => 'griddler/emails#create'

  constraints(SetupThredded.new) do
    root to: 'setups#new'
    get '/:step' => 'setups#new', constraints: { step: /\d{1}/ }, as: :new_setup
    post '/:step' => 'setups#create', constraints: { step: /\d{1}/ }, as: :create_setup
    resource :setup
  end

  resources :preferences

  match '/login' => redirect('/users/sign_in')
  match '/log_in' => redirect('/users/sign_in')
  match '/sign_in' => redirect('/users/sign_in')
  match '/logout' => redirect('/users/sign_out')
  match '/log_out' => redirect('/users/sign_out')
  match '/forgot_password' => redirect('/users/password/new')
  match '/user/forgot_password' => redirect('/users/password/new')
  match '/user/forgot_username' => redirect('/users/password/new')

  constraints(lambda{|req| req.env["QUERY_STRING"].include? 'q=' }) do
    get '/:messageboard_id(.:format)' => 'topics#search', as: :messageboard_search
  end

  get '/:messageboard_id/users' => 'users#index', as: :messageboard_users

  get '/:messageboard_id(.:format)' => 'topics#index', as: :messageboard_topics
  get '/:messageboard_id/topics/new/(:type)' => 'topics#new', as: :new_messageboard_topic
  get '/:messageboard_id/topics/category/:category_id' => 'topics#by_category', as: :messageboard_topics_by_category
  get '/:messageboard_id/:topic_id/edit(.:format)' => 'topics#edit', as: :edit_messageboard_topic
  put '/:messageboard_id/:topic_id(.:format)' => 'topics#update', as: :messageboard_topic
  post '/:messageboard_id/topics(.:format)' => 'topics#create', as: :create_messageboard_topic

  get '/:messageboard_id/private_topics/new/(:type)' => 'private_topics#new', as: :new_messageboard_private_topic
  get '/:messageboard_id/private_topics(.:format)' => 'private_topics#index', as: :messageboard_private_topics
  post '/:messageboard_id/private_topics(.:format)' => 'private_topics#create', as: :create_messageboard_private_topic

  get '/:messageboard_id/:topic_id(.:format)' => 'posts#index', as: :messageboard_topic_posts
  get '/:messageboard_id/:topic_id/posts(.:format)' => 'posts#index'
  get '/:messageboard_id/:topic_id/:post_id(.:format)' => 'posts#show', as: :messageboard_topic_post
  get '/:messageboard_id/:topic_id/:post_id/edit(.:format)' => 'posts#edit', as: :edit_messageboard_topic_post
  put '/:messageboard_id/:topic_id/:post_id(.:format)' => 'posts#update'
  post '/:messageboard_id/:topic_id/posts(.:format)' => 'posts#create', as: :create_messageboard_topic_post

  resources :messageboards do
    resources :topics do
      resources :posts
    end
  end

  root to: 'messageboards#index'
end

app/models/messageboard.rb
class Messageboard < ActiveRecord::Base
  SECURITY = %w{private logged_in public}
  PERMISSIONS = %w{members logged_in anonymous}

  attr_accessible :description,
    :name,
    :posting_permission,
    :security,
    :title

  default_scope where(closed: false).order('topics_count DESC')

  validates_numericality_of :topics_count
  validates_inclusion_of :security, in: SECURITY
  validates_inclusion_of :posting_permission, in: PERMISSIONS
  validates_presence_of :name, :title
  validates_format_of :name, with: /\A[\w\-]+\z/, on: :create,
    message: 'should be letters, nums, dash, underscore only.'
  validates_uniqueness_of :name,
    message: 'must be a unique board name. Try again.'
  validates_length_of :name, within: 1..16,
    message: 'should be between 1 and 16 characters'

  has_many :categories
  has_many :preferences
  has_many :posts
  has_many :roles
  has_many :topics
  has_many :private_topics
  has_many :users, through: :roles

  def add_member(user, as='member')
    roles.create(user_id: user.id, level: as)
  end

  def has_member?(user)
    roles.where(user_id: user.id).exists?
  end

  def member_is_a?(user, as)
    roles.where(user_id: user.id, level: as).exists?
  end

  def members_from_list(user_list)
    self.users.where('lower(name) in (?)', user_list.map(&:downcase))
  end

  def postable_by?(user)
    if self.posting_for_anonymous? && (self.restricted_to_private? || self.restricted_to_logged_in?)
        false
    else
      self.posting_for_anonymous? ||
        (self.posting_for_logged_in? && user.try(:valid?)) ||
        (self.posting_for_members? && user.try(:member_of?, self))
    end
  end

  def posting_for_anonymous?
    'anonymous' == posting_permission
  end

  def posting_for_logged_in?
    'logged_in' == posting_permission
  end

  def posting_for_members?
    'members' == posting_permission
  end

  def public?
    'public' == security
  end

  def restricted_to_logged_in?
    'logged_in' == security
  end

  def restricted_to_private?
    'private' == security
  end

  def to_param
    name.downcase
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  STATES = %w{pending approved}

  extend FriendlyId
  friendly_id :title, use: :scoped, scope: :messageboard
  paginates_per 50 if self.respond_to?(:paginates_per)

  has_many   :posts, include: :attachments
  has_many   :topic_categories
  has_many   :categories, through: :topic_categories

  belongs_to :last_user, class_name: 'User', foreign_key: 'last_user_id'
  belongs_to :user, counter_cache: true, touch: true
  belongs_to :messageboard, counter_cache: true, touch: true

  validates_inclusion_of :state, in: STATES
  validates_presence_of :hash_id
  validates_presence_of :last_user_id
  validates_presence_of :messageboard_id
  validates_numericality_of :posts_count
  validates_uniqueness_of :hash_id

  attr_accessible :category_ids,
    :last_user,
    :locked,
    :messageboard,
    :posts_attributes,
    :sticky,
    :type,
    :title,
    :user,
    :usernames

  accepts_nested_attributes_for :posts, reject_if: :updating?
  accepts_nested_attributes_for :categories

  default_scope order('updated_at DESC')

  delegate :name, :name=, :email, :email=, to: :user, prefix: true

  before_validation do
    if hash_id.nil?
      self.hash_id = SecureRandom.hex(10)
    end
  end

  def self.recent
    limit(10)
  end

  def self.stuck
    where('sticky = true')
  end

  def self.unstuck
    where('sticky = false OR sticky IS NULL')
  end

  def self.on_page(page_num)
    page(page_num).per(30)
  end

  def self.for_messageboard(messageboard)
    where(messageboard_id: messageboard.id)
  end

  def self.including_roles_for(user)
    joins(messageboard: :roles).where(roles: {user_id: user.id})
  end

  def self.public
    where('type is null')
  end

  def self.order_by_updated
    order('updated_at DESC')
  end

  def self.full_text_search(query, messageboard)
    if query.empty?
      []
    else
      sql_builder = SearchSqlBuilder.new(query, messageboard)
      sql = sql_builder.build
      sql_params = [sql].concat(sql_builder.binds)
      find_by_sql sql_params
    end
  end

  def last_user
    super || NullUser.new
  end

  def public?
    true
  end

  def private?
    false
  end

  def pending?
    state == 'pending'
  end

  def users
    []
  end

  def users_to_sentence
    ''
  end

  def self.inherited(child)
    child.instance_eval do
      def model_name
        Topic.model_name
      end
    end

    super
  end

  def self.select_options
    subclasses.map(&:to_s).sort
  end

  def updating?
    id.present?
  end

  def categories_to_sentence
    if categories
      categories.map(&:name).to_sentence
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :ensure_messageboard_exists

  def index
    if cannot? :read, messageboard
      error = 'You are not authorized access to this messageboard.'
      redirect_to default_home, flash: { error: error }
    else
      @sticky = get_sticky_topics
      @topics = get_topics
      @tracked_user_reads =
        UserTopicRead.statuses_for(current_user, @topics) || [NullTopicRead.new]
    end
  end

  def search
    @topics = get_search_results
    @tracked_user_reads = UserTopicRead.statuses_for(current_user, @topics)

    if @topics.empty?
      error = 'No topics found for this search.'
      redirect_to messageboard_topics_path(messageboard), flash: { error: error }
    end
  end

  def new
    @topic = messageboard.topics.build
    @topic.posts.build( filter: current_user.try(:post_filter) )

    unless can? :create, @topic
      error = 'Sorry, you are not authorized to post on this messageboard.'
      redirect_to messageboard_topics_path(messageboard), flash: { error: error }
    end
  end

  def by_category
    @sticky = get_sticky_topics
    @topics = get_topics_by_category params[:category_id]
    @category_name = Category.find(params[:category_id]).name
  end

  def create
    merge_default_topics_params
    @topic = messageboard.topics.create(params[:topic])
    redirect_to messageboard_topics_path(messageboard)
  end

  def edit
    authorize! :update, topic
  end

  def update
    params.deep_merge!({
      topic: {
        user: current_user,
        last_user: current_user
      }
    })

    topic.update_attributes(params[:topic])
    redirect_to messageboard_topic_posts_path(messageboard, topic)
  end

  private

  def get_search_results
    Topic.full_text_search(params[:q], messageboard)
  end

  def get_topics_by_category(category_id)
    Category.find(category_id)
      .topics
      .unstuck
      .for_messageboard(messageboard)
      .includes(:last_user)
      .order_by_updated
      .on_page(params[:page])
  end

  def get_topics
    Topic
      .unstuck
      .for_messageboard(messageboard)
      .public
      .includes(:user)
      .includes(:last_user)
      .on_page(params[:page])
  end

  def get_sticky_topics
    if on_first_topics_page?
      Topic
        .stuck
        .for_messageboard(messageboard)
        .order('id DESC')
    else
      []
    end
  end

  def on_first_topics_page?
    params[:page].nil? || params[:page] == '1'
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  require 'digest/md5'

  def md5(s)
    Digest::MD5.hexdigest(s)
  end

  def already_read(topic, tracked_user_reads)
    if tracked_user_reads
      topic_status = tracked_user_reads.select{ |t| t.topic_id == topic.id }.first
      if topic_status && topic_status.posts_count == topic.posts_count
        'read'
      else
        'unread'
      end
    end
  end
end

app/views/topics/_form.html.erb
<li class="title">
  <%= f.label :title %>
  <%= f.text_field :title, {
    placeholder: 'Title',
    tabindex: 1,
    autofocus: 'autofocus'
  } %>
</li>

<%= render 'topic_form', f: f, messageboard: messageboard %>

app/views/topics/_recent_topics_by_user.html.erb
<% if can? :read, topic %>
  <tr>
    <td class="title table-first-column"> <%= topic.title %> </td>
    <td class="replies"> <%= topic.posts_count %> </td>
    <td class="created"> <%= formatted_user_profile_date(topic.created_at) %> </td>
    <td class="updated"> <%= formatted_user_profile_date(topic.updated_at) %> </td>
  </tr>
<% end %>

app/views/topics/_topic_condensed.html.erb
<% topic = TopicDecorator.new(topic) %>

<article <%= topic.css_class %>>
  <div  class="post_count"><%= topic.posts_count %></div>

  <h1>
    <%= link_to topic.title, [messageboard, topic],
      class: already_read(topic, @tracked_user_reads) %>
  </h1>

  <cite class="updated_by">
    <%= topic.updated_at_timeago %>
    <%= topic.last_user_link %>
  </cite>

  <cite class="started_by">
    <%= topic.created_at_timeago %>
    <%= topic.user_link %>
  </cite>
</article>

app/views/topics/_topic_form.html.erb
<% if messageboard.categories.any? %>
  <li class="category">
    <%= f.select :category_ids, messageboard.category_options, {}, {
        multiple: true,
        'data-placeholder' => 'Categories',
        tabindex: 4
      } %>
  </li>
<% end %>

<% if signed_in? && current_user.admins?(messageboard) %>
  <li class="locked">
    <%= f.label :locked do %>
      Locked <%= f.check_box :locked %>
    <% end %>
  </li>

  <li class="sticky">
    <%= f.label :sticky do %>
      Sticky <%= f.check_box :sticky %>
    <% end %>
  </li>
<% end %>

<% if action_name != 'edit' %>
  <%= f.fields_for :posts do |post_form| %>
    <%= render 'posts/form', f: post_form %>
  <% end %>
<% end %>

app/views/topics/by_category.html.erb
<% content_for :page_id do %>topics_listing<% end %>
<% content_for :page_title do %><%= app_config.title %> | <%= messageboard.title %> | Recent Topics<% end %>

<header>
  <nav>
    <ul class="breadcrumbs">
      <li><%= link_to 'Forums', root_path %></li>
      <li><%= link_to messageboard.title, messageboard_topics_path(messageboard) %></li>
      <li><span><%= @category_name %></span></li>
    </ul>
  </nav>

  <%= render 'shared/currently_online' %>
  <%= render 'shared/topic_nav' %>
</header>

<section class="topics">
  <% if @sticky.any? %>
    <div class="stuck">
      <%= render partial: 'topics/topic_condensed', collection: @sticky, as: :topic %>
    </div>
  <% end %>

  <% if @topics.any? %>
    <div class="currently">
      <%= render partial: 'topics/topic_condensed', collection: @topics, as: :topic %>
    </div>
  <% end %>
</section>

<footer>
  <% if can? :create, messageboard.topics.build %>
    <%= link_to 'Create a New Topic', new_messageboard_topic_path(messageboard) %>
  <% end %>
</footer>

app/views/topics/edit.html.erb
<% content_for :page_id do %>topics_edit<% end %>
<% content_for :page_title do %>
  <%= app_config.title %> | <%= messageboard.title %> | Edit Topic
<% end %>

<header>
  <nav>
    <ul class="breadcrumbs">
      <li><a href="/">Forums</a></li>
      <li><%= link_to messageboard.title,
        messageboard_topic_posts_path(messageboard, topic) %></li>
      <li>
        <span>
          Editing Topic - <%= link_to topic.title, [messageboard, topic] %>
        </span>
      </li>
    </ul>
  </nav>
</header>

<div class="forms">
  <ul>
    <%= nested_form_for [@messageboard, @topic],
      url: messageboard_topic_path(@messageboard, @topic),
      html: { method: :put, class: :topic_form, multipart: true } do |f| %>

      <%= render 'form', f: f, messageboard: MessageboardDecorator.new(messageboard) %>

      <li class="submit">
        <%= f.submit 'Update Topic' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/topics/index.html.erb
<% content_for :page_id do %>topics_listing<% end %>
<% content_for :page_title do %>
  <%= app_config.title %> | <%= messageboard.title %> | Recent Topics
<% end %>

<header>
  <nav>
    <ul class="breadcrumbs">
      <li><%= link_to 'Forums', root_path %></li>
      <li><span><%= messageboard.title %></span></li>
    </ul>
  </nav>

  <%= render 'shared/currently_online' %>
  <%= render 'shared/topic_nav' %>
</header>

<section class="topics">
  <% if @sticky.first %>
    <div class="stuck">
      <%= render partial: 'topics/topic_condensed', collection: @sticky, as: :topic %>
    </div>
  <% end %>

  <% if @topics.first %>
    <div class="currently">
      <%= render partial: 'topics/topic_condensed', collection: @topics, as: :topic %>
    </div>
  <% end %>
</section>

<footer>
  <%= paginate @topics %>
  <nav>
    <% if can? :create, messageboard.topics.build %>
      <ul class="actions">
        <li><%= link_to 'Create a New Topic', new_messageboard_topic_path(messageboard) %></li>
      </ul>
    <% end %>

    <ul class="breadcrumbs">
      <li><%= link_to 'Forums', root_path %></li>
      <li><span><%= messageboard.title %></span></li>
    </ul>
  </nav>
</footer>

app/views/topics/new.html.erb
<% content_for :page_id do %>topics_new<% end %>
<% content_for :page_title do %>
  <%= app_config.title %> | <%= messageboard.title %> | start a new topic
<% end %>

<header>
  <nav>
    <ul class="breadcrumbs">
      <li><a href="/">Forums</a></li>
      <li><%= link_to messageboard.title,
        messageboard_topics_path(messageboard) %></li>
      <li><span>New Topic</span></li>
    </ul>
  </nav>
</header>

<div class="forms">
  <%= nested_form_for( [messageboard, @topic],
    url: create_messageboard_topic_url(messageboard, @topic),
    html: { multipart: true, class: :topic_form }) do |f| %>

    <ul>
      <%= render 'form', f: f, messageboard: MessageboardDecorator.new(messageboard) %>

      <li class="submit">
        <%= f.submit 'Create New Topic', { tabindex: 3 } %>
      </li>
    </ul>
  <% end %>
</div>

app/views/topics/search.html.erb
<% content_for :page_id do %>topics_listing<% end %>
<% content_for :page_title do %>
  <%= app_config.title %> | <%= messageboard.title %> | Search Results
<% end %>

<header>
  <nav>
    <ul class="breadcrumbs">
      <li><%= link_to 'Forums', root_path %></li>
      <li><%= link_to messageboard.title, messageboard_topics_path(messageboard) %></li>
      <li><span>Results for "<%= params[:q]%>"</span></li>
    </ul>
  </nav>

  <%= render 'shared/currently_online' %>
  <%= render 'shared/topic_nav' %>
</header>

<section class="topics">
  <div class="currently">
    <%= render partial: 'topics/topic_condensed', collection: @topics, as: :topic %>
  </div>
</section>

<footer>
  <nav>
    <% if can? :create, messageboard.topics.build %>
      <ul class="actions">
        <li><%= link_to 'Create a New Topic', new_messageboard_topic_path(messageboard) %></li>
      </ul>
    <% end %>

    <ul class="breadcrumbs">
      <li><%= link_to 'Forums', root_path %></li>
      <li><span><%= messageboard.title %></span></li>
    </ul>
  </nav>
</footer>

app/views/topics/show.html.erb
<% content_for :page_id do %>topics_posts<% end %>
<% content_for :page_title do %><%= site.title %> | <%= topic.title %> | Posts<% end %>
<% content_for :header_nav do %>
    <nav>
      <ul>
        <%= render :partial => 'search/form' %>
        <% if messageboard.posting_for_anonymous? || (current_user && current_user.can_post_to?(messageboard)) -%>
          <li class="new_topic"><%= link_to "Create a New Topic", new_messageboard_topic_path(messageboard) %></li>
          <li class="reply_to_topic"><a href="#new_post">Reply To This Topic</a></li>
        <% end -%>
        <% if (current_user && current_user.admins?(messageboard)) || topic.user == current_user  -%>
          <li class="edit_topic"><%= link_to "edit subject", edit_messageboard_topic_path(messageboard, topic) %></li>
        <% end -%>
      </ul>
    </nav>
<% end %>

  <header>
    <nav class="breadcrumbs">
      <ul>
        <li><a href="/">Forums</a> &rarr; </li>
        <li><%= link_to messageboard.title, messageboard_path(messageboard) %> &rarr; </li>
      </ul>
    </nav>
    <h1><%= topic.title %></h1> 
    <h2><%= topic.posts_count %> posts</h2>
    <% if topic.users_to_sentence %>
      <cite><%= topic.users_to_sentence %></cite>
    <% end %>
  </header>

  <%= render topic.posts %>
  
  <% if messageboard.posting_for_anonymous? || (current_user && current_user.can_post_to?(messageboard)) -%>
    <%= nested_form_for([messageboard, topic, @post], :html => { :multipart => true }) do |f| %>
      <p>
        <%= f.label :your_reply %>
        <%= f.text_area :content, :rows => 5 %>
      </p>

      <%= f.fields_for :attachments do |attachment_form|  %>
        <p class="attachment"> <%= attachment_form.file_field :attachment %><%= attachment_form.link_to_remove "Remove this attachment", :class => "remove_attachment" %> </p>
      <% end %>
      <%= f.link_to_add "Add an attachment", :attachments, :class => "add_attachment" %>
      <%= f.select :filter, @post.filters %>

      <%= f.submit "Submit a reply" %>
    <% end -%>
  <% end -%>

  <footer>
    <nav class="breadcrumbs">
      <ul>
        <li><a href="/">Forums</a> &rarr; </li>
        <li><%= link_to messageboard.title, messageboard_path(messageboard) %> &rarr; </li>
      </ul>
    </nav>
  </footer>